GuantesWario/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('informacion','InformacionCtrl');
Route::resource('tienda','TiendaCtrl');
Route::get('tiendaCategoria/{id}','TiendaCtrl@index');
Route::resource('contacto','ContactoCtrl');
Route::resource('carrito','CarritoCtrl');
Route::resource('loginAdmin','loginAdminCtrl');
Route::resource('inicioAdmin','inicioAdminCtrl');
Route::resource('pagos','pagosCtrl');
Route::resource('categorias','categoriasCtrl');
//URL para editar categorias con metodo Ajax.
Route::post('/editar/categorias','categoriasCtrl@editarCategoria');
//URL para actualizar datos
Route::post('/actualizar/categorias','categoriasCtrl@actualizarCategoria');
Route::resource('administradores','administradoresCtrl');
Route::resource('clientes','clientesCtrl');
Route::resource('productos','productosCtrl');
//URL para editar productos con metodo Ajax.
Route::post('/editar/productos','productosCtrl@editarProducto');
//URL para actualizar datos de productos
Route::post('/actualizar/productos','productosCtrl@actualizarProducto');
Route::resource('ventas','ventasCtrl');
//URL para editar ventas con metodo Ajax.
Route::post('/editar/ventas','ventasCtrl@editarVenta');
//URL para actualizar datos de venta
Route::post('/actualizar/ventas','ventasCtrl@actualizarVenta');

GuantesWario/resources/views/admin/categorias.blade.php
@extends('template2')

@section('contenido')
<section class="full-width pageContent">
		<section class="full-width header-well">
			<div class="full-width header-well-icon">
				<i class="zmdi zmdi-label"></i>
			</div>
			<div class="full-width header-well-text">
				<p class="text-condensedLight">
					Agrega las categorías de los productos disponibles.
				</p>
			</div>
		</section>
		<div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
			<div class="mdl-tabs__tab-bar">
				<a href="#tabNewCategory" class="mdl-tabs__tab is-active">Nueva categoría</a>
				<a href="#tabListCategory" class="mdl-tabs__tab">Lista de categorías</a>
			</div>
			<div class="mdl-tabs__panel is-active" id="tabNewCategory">
				<div class="mdl-grid">
					<div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--8-col-desktop mdl-cell--2-offset-desktop">
						<div class="full-width panel mdl-shadow--2dp">
							<div class="full-width panel-tittle bg-primary text-center tittles">
								Nueva categoría
							</div>
							<div class="full-width panel-content">
								<form action="{{route('categorias.store')}}" method="post">
									@csrf
									<h5 class="text-condensedLight">Datos de la categoría</h5>
									<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
										<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="Nombre" name="NombreCategoria">
										<label class="mdl-textfield__label" for="Nombre">Nombre</label>
										<span class="mdl-textfield__error">Nombre no válido</span>
									</div>
									<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
										<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-záéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="Descripcion" name="DescripcionCategoria">
										<label class="mdl-textfield__label" for="Descripcion">Descripción</label>
										<span class="mdl-textfield__error">Descripción no valida</span>
									</div>
									<p class="text-center">
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored bg-primary" id="btn-addCategory" type="submit">
											<i class="zmdi zmdi-plus"></i>
										</button>
										<div class="mdl-tooltip" for="btn-addCategory">Añadir categoría</div>
									</p>
								</form>
							</div>

						</div>
					</div>
				</div>
			</div>
			<div class="mdl-tabs__panel" id="tabListCategory">
				<div class="mdl-grid">
					<div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--8-col-desktop mdl-cell--2-offset-desktop">
						<div class="full-width panel mdl-shadow--2dp">
							<div class="full-width panel-tittle bg-success text-center tittles">
								Lista de categorías
							</div>
							<div class="full-width panel-content">
								<form action="#">
									<div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
										<label class="mdl-button mdl-js-button mdl-button--icon" for="searchCategory">
											<i class="zmdi zmdi-search"></i>
										</label>
										<div class="mdl-textfield__expandable-holder">
											<input class="mdl-textfield__input" type="text" id="searchCategory">
											<label class="mdl-textfield__label"></label>
										</div>
									</div>
								</form>
								<div class="container">
									<table class="table table-bordered table-responsive">
										<thead>
											<tr>
												<th>ID</th>
												<th>NOMBRE</th>
												<th>DESCRIPCIÓN</th>
												<th>OPCION</th>
											</tr>
										</thead>
										<tbody>
											@foreach($categorias as $categoria)
											<tr class="mdl-data-table tbody tr:hover">
											<td>{{$categoria->id}}</td>
											<td>{{$categoria->nombre}}</td>
											<td>{{$categoria->descripcion}}</td>
											<td> 
											    <div class="row">
													<div class="col-lg-6 col-md-6 col-sm-6 col-6">
                                	                <button type="text" data-bs-toggle="modal" data-bs-target="#editarModal" onclick="editar({{$categoria->id}})" class="btn text-white" style="background-color: #207671;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-diff-fill" viewBox="0 0 16 16">
                                	                <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM8 6a.5.5 0 0 1 .5.5V8H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V9H6a.5.5 0 0 1 0-1h1.5V6.5A.5.5 0 0 1 8 6zm-2.5 6.5A.5.5 0 0 1 6 12h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5z"/>
                                	                </svg></button>
                             					</div>
												<div class="col-lg-6 col-md-6 col-sm-6 col-6">
                                                	<form action="{{url('/categorias/'.$categoria->id)}}" class="formulario-eliminar" method="POST">
                                                	@csrf  
                                                	@method('DELETE')
                                                	<button class="btn btn-danger" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                                	<path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                                	</svg></button>
                                                	</form>
                                                </div>
												</div>
											</td>
											</tr>
											@endforeach
										</tbody>
									</table>
								</div>
							</div>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Modal -->
<div class="modal fade" id="editarModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Actualizar datos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
	  <div class="full-width panel-content">
			<form id="formularioEditar">
				@csrf
				<input type="hidden" id="idModal">
				<h5 class="text-condensedLight">Datos de la categoría</h5>
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				    <label  for="Nombre">Nombre</label>
					<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="nombreModal" name="NombreCategoriaModal">	
					<span class="mdl-textfield__error">Nombre no válido</span>
					
				</div>
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				    <label for="Descripcion">Descripción</label>
					<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-záéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="descripcionModal" name="DescripcionCategoriaModal">		
					<span class="mdl-textfield__error">Descripción no valida</span>
				</div>
				<button type="submit" class="btn btn-primary">Guardar Cambios</button>
				
			</form>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        
      </div>
    </div>
  </div>
</div>
@endsection
@section('javascript')
<script>
	function editar(id)
	{
		$(document).ready(function(){
            $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
            $.ajax({
            url:'/editar/categorias',
            method:'POST',
            data:{
            id:id
            } 
            }).done(function(respuesta){

		    var arreglo = JSON.parse(respuesta);
			
			$("#idModal").val(arreglo[0].id);
			$("#nombreModal").val(arreglo[0].nombre);
			$("#descripcionModal").val(arreglo[0].descripcion);
            });
        });
	}
</script>
<script>
    $('#formularioEditar').submit(function(e){
          e.preventDefault();
          $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
        var idM = $('#idModal').val();
        var nombreM = $('#nombreModal').val();
        var descripcionM = $('#descripcionModal').val();
        $.ajax({
          url:'/actualizar/categorias',
          method:'POST',
          data:{
            id:idM,
            nombre:nombreM,
			descripcion:descripcionM,
          } 
        }).done(function(){                  
          location.reload();
        });
    });
</script>
@endsection

GuantesWario/resources/views/admin/inicioAdmin.blade.php
@extends('template2')

@section('contenido')
<!-- pageContent -->
<section class="full-width pageContent">
		<section class="full-width text-center" style="padding: 40px 0;">
			<h3 class="text-center tittles">Consulta rápida</h3>
			<!-- Tiles -->
			<article class="full-width tile">
				<div class="tile-text">
					<span class="text-condensedLight">
						2<br>
						<small>Administradores</small>
					</span>
				</div>
				<i class="zmdi zmdi-account tile-icon"></i>
			</article>
			<article class="full-width tile">
				<div class="tile-text">
					<span class="text-condensedLight">
						71<br>
						<small>Clientes</small>
					</span>
				</div>
				<i class="zmdi zmdi-accounts tile-icon"></i>
			</article>
			<article class="full-width tile">
				<div class="tile-text">
					<span class="text-condensedLight">
						9<br>
						<small>Categorias</small>
					</span>
				</div>
				<i class="zmdi zmdi-label tile-icon"></i>
			</article>
			<article class="full-width tile">
				<div class="tile-text">
					<span class="text-condensedLight">
						121<br>
						<small>Productos</small>
					</span>
				</div>
				<i class="zmdi zmdi-washing-machine tile-icon"></i>
			</article>
			<article class="full-width tile">
				<div class="tile-text">
					<span class="text-condensedLight">
						47<br>
						<small>Ventas</small>
					</span>
				</div>
				<i class="zmdi zmdi-shopping-cart tile-icon"></i>
			</article>
		</section>
		
	</section>
@endsection

GuantesWario/resources/views/admin/productos.blade.php
@extends('template2')

@section('contenido')
<section class="full-width pageContent">
		<section class="full-width header-well">
			<div class="full-width header-well-icon">
				<i class="zmdi zmdi-washing-machine"></i>
			</div>
			<div class="full-width header-well-text">
				<p class="text-condensedLight">
					Agrega nuevos productos para que tus clientes puedan verlos en el catálago de productos.
				</p>
			</div>
		</section>
		<div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
			<div class="mdl-tabs__tab-bar">
				<a href="#tabNewProduct" class="mdl-tabs__tab is-active">Nuevo producto</a>
				<a href="#tabListProducts" class="mdl-tabs__tab">Lista de productos</a>
			</div>
			<div class="mdl-tabs__panel is-active" id="tabNewProduct">
				<div class="mdl-grid">
					<div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--12-col-desktop">
						<div class="full-width panel mdl-shadow--2dp">
							<div class="full-width panel-tittle bg-primary text-center tittles">
								Nuevo Producto
							</div>
							<div class="full-width panel-content">
								<form action="{{route('productos.store')}}" method="post" enctype="multipart/form-data">
								@csrf
									<div class="mdl-grid">
										<div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--6-col-desktop">
											<h5 class="text-condensedLight">Información básica</h5>
											
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
												<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="nombreP" name="nombreProducto">
												<label class="mdl-textfield__label" for="nombreP">Nombre</label>
												<span class="mdl-textfield__error">Nombre inválido</span>
											</div>
											<div class="mdl-textfield mdl-js-textfield">
												<select class="mdl-textfield__input" id="categoriaP" name="categoriaProducto">
													<option>Seleccionar categoría</option>
													@foreach($categorias as $categoria)
													<option>{{$categoria->nombre}}</option>
													@endforeach
												</select>
											</div>
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
												<input class="mdl-textfield__input" type="text" pattern="-?[0-9.]*(\.[0-9]+)?" id="precioP" name="precioProducto">
												<label class="mdl-textfield__label" for="precioP">Precio</label>
												<span class="mdl-textfield__error">Precio inválido</span>
											</div>
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
												<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="tallaP" name="tallaProducto">
												<label class="mdl-textfield__label" for="tallaP">Talla</label>
												<span class="mdl-textfield__error">Talla inválida</span>
											</div>	
										</div>
										<div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--6-col-desktop">
											<h5 class="text-condensedLight">Agrega una imágen del producto</h5>
											<div class="mdl-textfield mdl-js-textfield">
												<input type="file" name="imagen">
											</div>
											
										</div>
										<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
												<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="descripcionP" name="descripcionProducto">
												<label class="mdl-textfield__label" for="descripcionP">Descripción</label>
												<span class="mdl-textfield__error">Descripcion invalida</span>
										</div>
									</div>
									<p class="text-center">
										<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored bg-primary" id="btn-addProduct">
											<i class="zmdi zmdi-plus"></i>
										</button>
										<div class="mdl-tooltip" for="btn-addProduct">Añadir producto</div>
									</p>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="mdl-tabs__panel" id="tabListProducts">
				<div class="mdl-grid">
					<div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--12-col-desktop">
						<form action="#">
							<div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
								<label class="mdl-button mdl-js-button mdl-button--icon" for="searchProduct">
									<i class="zmdi zmdi-search"></i>
								</label>
								<div class="mdl-textfield__expandable-holder">
									<input class="mdl-textfield__input" type="text" id="searchProduct">
									<label class="mdl-textfield__label"></label>
								</div>
							</div>
						</form>
						<nav class="full-width menu-categories">
						<div class="mdl-textfield mdl-js-textfield">
						<form action="{{route('productos.index',$categoria->nombre)}}">
							<select class="mdl-textfield__input" id="categoriaP" name="categoriaProducto">
								<option>Seleccionar categoría</option>
								@foreach($categorias as $categoria)
								<option>{{$categoria->nombre}}</option>
								@endforeach
							</select>
							<button type="submit" class="btn btn-success">Ver productos</button>
                        </form>
						</div>
						</nav>
						@foreach($productos as $producto)
						<div class="full-width text-center" style="padding: 30px 0;">
						
							<div class="mdl-card mdl-shadow--2dp full-width product-card">
							
								<div class="mdl-card__title">
									<img src="img/Productos/{{$producto->imagen}}" alt="product" class="img-responsive">
								</div>
								<div class="mdl-card__supporting-text">
									<small>Talla:{{$producto->talla}}</small><br>
									<small>{{$producto->precio}}</small>
								</div>
								<div class="mdl-card__actions mdl-card--border">
								{{$producto->nombreP}}
									<button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
										<i class="zmdi zmdi-more"></i>
									</button>
								</div>
								<div class="row">
									<div class="col-lg-6 col-md-6 col-sm-6 col-6">
                                    <a href="{{url('/productos/'.$producto->id.'/edit')}}" class="btn text-white" style="background-color: #207671;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-diff-fill" viewBox="0 0 16 16">
                                    <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM8 6a.5.5 0 0 1 .5.5V8H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V9H6a.5.5 0 0 1 0-1h1.5V6.5A.5.5 0 0 1 8 6zm-2.5 6.5A.5.5 0 0 1 6 12h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5z"/>
                                    </svg></a>
                             	</div>
								<div class="col-lg-6 col-md-6 col-sm-6 col-6">
                                	<form action="{{url('/productos/'.$producto->id)}}" class="formulario-eliminar" method="POST">
                                	@csrf  
                                	@method('DELETE')
                                	<button class="btn btn-danger" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                	<path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                	</svg></button>
                                	</form>
                                </div>
												
					   
							</div>
							
						</div>
						@endforeach			
									
						
					</div>
				</div>
			</div>
		</div>
	</section>
<!-- Modal -->
<div class="modal fade" id="editarModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Actualizar datos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
	  <div class="full-width panel-content">
			<form id="formularioEdit"  enctype="multipart/form-data" method="post">
			@csrf
			
				<input type="hidden" id="idModal">
				<h5 class="text-condensedLight">Datos del producto</h5>
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				    <label for="nombreP">Nombre</label>
					<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="nombreModal" name="nombreProductoModal">	
					<span class="mdl-textfield__error">Nombre inválido</span>
				</div>
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				    <label for="categoriaP">Categoria</label>
					<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="categoriaModal" name="categoriaProductoModal">
					
					<span class="mdl-textfield__error">Nombre inválido</span>
				</div>
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
					<label for="precioP">Precio</label>
					<input class="mdl-textfield__input" type="text" pattern="-?[0-9.]*(\.[0-9]+)?" id="precioModal" name="precioProductoModal">
					
					<span class="mdl-textfield__error">Precio inválido</span>
				</div>
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
					<label for="tallaP">Talla</label>
					<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="tallaModal" name="tallaProductoModal">
					
					<span class="mdl-textfield__error">Talla inválida</span>
				</div>	
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<label for="descripcionP">Descripción</label>
					<input class="mdl-textfield__input" type="text" pattern="-?[A-Za-z0-9áéíóúÁÉÍÓÚ ]*(\.[0-9]+)?" id="descripcionPModal" name="descripcionProductoModal">
					
					<span class="mdl-textfield__error">Descripcion invalida</span>
				</div>
				<div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--6-col-desktop">
					<h5 class="text-condensedLight">Imágen del producto</h5>
					<div class="mdl-textfield mdl-js-textfield">
						
						<input class="mdl-textfield__input" type="text" id="imagenPModal" name="imagenPPModal">
						<input type="file" id="imagenModal" name="imagenProductoModal">
					</div>		
				</div>				
				<button type="submit" class="btn btn-primary">Guardar Cambios</button>			
			</form>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        
      </div>
    </div>
  </div>
</div>
@endsection
@section('javascript')
<script>
	function editar(id)
	{
		$(document).ready(function(){
            $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
            $.ajax({
            url:'/editar/productos',
            method:'POST',
            data:{
            id:id
            } 
            }).done(function(respuesta){
				//alert(respuesta);
		    var arreglo = JSON.parse(respuesta);
			
			$("#idModal").val(arreglo[0].id);
			$("#nombreModal").val(arreglo[0].nombreP);
			$("#categoriaModal").val(arreglo[0].categoria);
			$("#precioModal").val(arreglo[0].precio);
			$("#tallaModal").val(arreglo[0].talla);
			$("#imagenPModal").val(arreglo[0].imagen);
			$("#descripcionPModal").val(arreglo[0].descripcion);
            });
        });
	}
</script>
<script>
    $('#formularioEdit').submit(function(e){
          e.preventDefault();
          $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
        var idM = $('#idModal').val();
        var nombreM = $('#nombreModal').val();
        var categoriaM = $('#categoriaModal').val();
		var precioM = $('#precioModal').val();
		var tallaM = $('#tallaModal').val();
		var imagenM = $('#imagenModal').val();
		var descripcionM = $('#descripcionModal').val();
        $.ajax({
          url:'/actualizar/productos',
		  method:'POST',
          data:{
            id:idM,
            nombre:nombreM,
			categoria:categoriaM,
			precio:precioM,
			talla:tallaM,
			imagen:imagenM,
			descripcion:descripcionM,
          } 
        }).done(function(e){                  
          //alert(e);
		  location.reload();
        });
    });
</script>
@endsection