GuantesWario/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('informacion','InformacionCtrl');
Route::resource('tienda','TiendaCtrl');
Route::get('tiendaCategoria/{id}','TiendaCtrl@index');
Route::resource('contacto','ContactoCtrl');
Route::resource('carrito','CarritoCtrl');
Route::resource('loginAdmin','loginAdminCtrl');
Route::resource('inicioAdmin','inicioAdminCtrl');
Route::resource('pagos','pagosCtrl');
Route::resource('categorias','categoriasCtrl');
//URL para editar categorias con metodo Ajax.
Route::post('/editar/categorias','categoriasCtrl@editarCategoria');
//URL para actualizar datos
Route::post('/actualizar/categorias','categoriasCtrl@actualizarCategoria');
Route::resource('administradores','administradoresCtrl');
Route::resource('clientes','clientesCtrl');
Route::resource('productos','productosCtrl');
//URL para editar productos con metodo Ajax.
Route::post('/editar/productos','productosCtrl@editarProducto');
//URL para actualizar datos de productos
Route::post('/actualizar/productos','productosCtrl@actualizarProducto');
Route::resource('ventas','ventasCtrl');
//URL para editar ventas con metodo Ajax.
Route::post('/editar/ventas','ventasCtrl@editarVenta');
//URL para actualizar datos de venta
Route::post('/actualizar/ventas','ventasCtrl@actualizarVenta');

GuantesWario/resources/views/carrito.blade.php
@extends('template1')

@section('content')
<section class="container py-5">
        <table class="table table-responsive table-striped table-bordered">
            <thead>
                <tr>
                    
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Subtotal</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    
                    <td>Pechera industrial</td>
                    <td>80.00</td>
                    <td>2</td>
                    <td>160.00</td>
                    <td><button type="submit" class="btn btn-danger btn-lg px-3">Eliminar</button></td>
                </tr>
                
            </tbody>
        </table>
        <div class="row">
            <div class="col text-end mt-2">
                <button type="submit" class="btn btn-outline-primary btn-lg px-3">Generar PDF</button>
            </div>
        </div>
    </section>
    <!-- End Section -->
    <!-- Start Contact -->
    <div class="container py-5 bg-light">
                  
            <form action="{{route('clientes.store')}}" class="col-md-9 m-auto" method="post" role="form">
                @csrf
                <p>Llena los siguientes datos y envía tu cotización con el archivo generado.</p>
                <div class="row">                  
                    <div class="form-group col-md-6 mb-3">
                        <label for="inputname">Nombre</label>
                        <input type="text" class="form-control mt-1" id="name" name="nombreC" placeholder="Nombre">
                    </div>
                    <div class="form-group col-md-6 mb-3">
                        <label for="inputemail">E-mail</label>
                        <input type="email" class="form-control mt-1" id="email" name="email" placeholder="E-mail">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="inputsubject">Razón social</label>
                    <input type="text" class="form-control mt-1" id="subject" name="razon" placeholder="Razón Social">
                </div>
                <div class="mb-3">
                    <label for="inputsubject">RFC</label>
                    <input type="text" class="form-control mt-1" id="subject" name="rfc" placeholder="RFC">
                </div>
                <div class="mb-3">
                    <label for="inputsubject">Dirección</label>
                    <input type="text" class="form-control mt-1" id="subject" name="direccion" placeholder="Dirección">
                </div>
                <div class="mb-3">
                    <label for="inputsubject">Teléfono</label>
                    <input type="text" class="form-control mt-1" id="subject" name="telefono" placeholder="Teléfono">
                </div>
                <div class="row">
                    <div class="col text-end mt-2">
                        <button type="submit" class="btn btn-success btn-lg px-3">Envíar</button>
                    </div>
                </div>
            </form>
        
    </div>
    <!-- End Contact -->
@endsection

GuantesWario/resources/views/contacto.blade.php
@extends('template1')

@section('content')
<!-- Start Content Page -->
<div class="container-fluid bg-light py-5">
        <div class="col-md-6 m-auto text-center">
            <h1 class="h1">Ponte en contacto con nosotros</h1>
            <p>
                Visitanos en la dirección marcada en el mapa.
            </p>
        </div>
    </div>

    <!-- Start Map -->
    <div id="mapid" style="width: 100%; height: 300px;"></div>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
    <script>
        var mymap = L.map('mapid').setView([21.376499, -101.926586, 13], 13);

        L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
            maxZoom: 18,
            attribution: 'Zay Telmplte | Template Design by <a href="https://templatemo.com/">Templatemo</a> | Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1
        }).addTo(mymap);

        L.marker([-23.013104, -43.394365, 13]).addTo(mymap)
            .bindPopup("<b>Zay</b> eCommerce Template<br />Location.").openPopup();

        mymap.scrollWheelZoom.disable();
        mymap.touchZoom.disable();
    </script>
    <!-- Ena Map -->

    <!-- Start Contact -->
    <div class="container py-5">
        <div class="row py-5">
            <form class="col-md-9 m-auto" method="post" role="form">
                <div class="row">
                    <div class="form-group col-md-6 mb-3">
                        <label for="inputname">Nombre</label>
                        <input type="text" class="form-control mt-1" id="name" name="name" placeholder="Name">
                    </div>
                    <div class="form-group col-md-6 mb-3">
                        <label for="inputemail">E-mail</label>
                        <input type="email" class="form-control mt-1" id="email" name="email" placeholder="Email">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="inputsubject">Asunto</label>
                    <input type="text" class="form-control mt-1" id="subject" name="subject" placeholder="Subject">
                </div>
                <div class="mb-3">
                    <label for="inputmessage">Mensaje</label>
                    <textarea class="form-control mt-1" id="message" name="message" placeholder="Message" rows="8"></textarea>
                </div>
                <div class="row">
                    <div class="col text-end mt-2">
                        <button type="submit" class="btn btn-success btn-lg px-3">Envíar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- End Contact -->
@endsection

GuantesWario/resources/views/home.blade.php
@extends('template1')

@section('content')
<!-- Start Banner Hero -->
<div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
        <ol class="carousel-indicators">
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="img/guantes.jpeg" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left align-self-center">
                                <h1 class="h1 text-success"> Guantes industriales <b>Wario</b></h1>
                                <h3 class="h2">Guantes</h3>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="img/antebraceras.jpeg" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left">
                                <h1 class="h1 text-success"> Guantes industriales <b>Wario</b></h1>
                                <h3 class="h2">Antebraceras</h3>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="img/pecheras.jpeg" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left">
                                <h1 class="h1 text-success"> Guantes industriales <b>Wario</b></h1>
                                <h3 class="h2">Pecheras</h3>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="img/chamarras.jpg" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left">
                                <h1 class="h1 text-success"> Guantes industriales <b>Wario</b></h1>
                                <h3 class="h2">Chamarras</h3>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="img/polainas.jpg" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left">
                                <h1 class="h1 text-success"> Guantes industriales <b>Wario</b></h1>
                                <h3 class="h2">Polainas</h3>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev text-decoration-none w-auto ps-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="prev">
            <i class="fas fa-chevron-left"></i>
        </a>
        <a class="carousel-control-next text-decoration-none w-auto pe-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="next">
            <i class="fas fa-chevron-right"></i>
        </a>
    </div>
    <!-- End Banner Hero -->


    <!-- Start Categories of The Month -->
    <section class="container py-5">
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">Categorías de los productos disponibles</h1>
                <p>
                    Navega dentro de las categorías y encuentra lo que estás buscando.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-4 p-5 mt-3">
                <a href="#"><img src="img/guantes.jpeg" class="rounded-circle img-fluid border"></a>
                <h5 class="text-center mt-3 mb-3">GUANTES</h5>
                <p class="text-center"><a href="tienda" class="btn btn-success">Ir a la tienda</a></p>
            </div>
            <div class="col-12 col-md-4 p-5 mt-3">
                <a href="#"><img src="img/antebraceras.jpeg" class="rounded-circle img-fluid border"></a>
                <h2 class="h5 text-center mt-3 mb-3">ANTEBRACERAS</h2>
                <p class="text-center"><a href="tienda" class="btn btn-success">Ir a la tienda</a></p>
            </div>
            <div class="col-12 col-md-4 p-5 mt-3">
                <a href="#"><img src="img/pecheras.jpeg" class="rounded-circle img-fluid border"></a>
                <h2 class="h5 text-center mt-3 mb-3">PECHERAS</h2>
                <p class="text-center"><a href="tienda" class="btn btn-success">Ir a la tienda</a></p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-2 p-5 mt-3">
            </div>
            <div class="col-12 col-md-4 p-5 mt-3">
                <a href="#"><img src="img/chamarras.jpg" class="rounded-circle img-fluid border"></a>
                <h5 class="text-center mt-3 mb-3">CHAMARRAS</h5>
                <p class="text-center"><a href="tienda" class="btn btn-success">Ir a la tienda</a></p>
            </div>
            <div class="col-12 col-md-4 p-5 mt-3">
                <a href="#"><img src="img/polainas.jpg" class="rounded-circle img-fluid border"></a>
                <h2 class="h5 text-center mt-3 mb-3">POLAINAS</h2>
                <p class="text-center"><a href="tienda" class="btn btn-success">Ir a la tienda</a></p>
            </div>
            <div class="col-12 col-md-2 p-5 mt-3">
            </div>
        </div>
    </section>
    <!-- End Categories of The Month -->
@endsection

GuantesWario/resources/views/informacion.blade.php
@extends('template1')

@section('content')
<section class="bg-success py-5">
        <div class="container">
            <div class="row align-items-center py-5">
                <div class="col-md-8 text-white">
                    <h1 class="text-center">Acerca de nosotros</h1>
                    <p class="text-center">
                    Somos fabricantes con más de 25 años de experiencia en la manufactura de equipo de protección industrial, con presencia en todo el país.

Guantes Industriales Wario nos especializamos en la fabricación de equipo de protección personal de calidad a un precio justo en materiales como carnaza, piel, mezclilla, aluminio, kevlar, entre otros.

Somos la mejor opción en precio, calidad y servicio tanto para grandes o pequeñas empresas.
                    </p>
                </div>
                <div class="col-md-4">
                    <img src="img/logo.jpeg" alt="About Hero">
                </div>
            </div>
        </div>
    </section>
    <!-- Close Banner -->

    <!-- Start Section -->
    <section class="container py-5">
        <div class="row text-center pt-5 pb-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">Conocenos un poco más</h1>
                <p>
                    Misión, Visión y Valores de nuestra organización.
                </p>
            </div>
        </div>
        <div class="row">

            <div class="col-md-6 col-lg-4 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fas fa-book-open"></i></div>
                    <h2 class="h5 mt-4 text-center">Misión</h2>
                    <p class="text-center">
                        OFRECER A NUESTROS CLIENTES PRODUCTOS DE SEGURIDAD INDUSTRIAL, DISEÑADOS Y DESARROLLADOS PARA SATISFACER NECESIDADES Y EXPECTATIVAS A PRECIO JUSTO Y EXCELENTE SERVICIO.
                    </p>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fas fa-eye"></i></div>
                    <h2 class="h5 mt-4 text-center">Visión</h2>
                    <P class="text-center"> 
                        SER UNA EMPRESA DESTACADA POR SU INNOVACIÓN Y CALIDAD DENTRO DEL SECTOR INDUSTRIAL, CUBRIENDO LAS NECESIDADES DE NUESTROS CLIENTES, LOGRANDO DE ESTA MANERA UN ALTO NIVEL DE PRODUCTIVIDAD Y RENTABILIDAD PARA CONSOLIDARNOS COMO LÍDERES DENTRO DEL MERCADO.
                    </P>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fas fa-handshake"></i></div>
                    <h2 class="h5 mt-4 text-center">Valores</h2>
                    <P class="text-center">
                        COMPROMISO <BR> SERIEDAD <BR> HONESTIDAD <BR> RESPONSABILIDAD
                    </P>
                </div>
            </div>
        </div>
    </section>
    <!-- End Section -->

    <!-- Start Brands --> <!--Me gustaría poner un Modal aquí para el contenido de lo anterior-->
    
    <!--End Brands-->
@endsection

GuantesWario/resources/views/template2.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<title>Administradores</title>
	<link rel="stylesheet" href="css/normalize.css">
	<link rel="stylesheet" href="css/sweetalert2.css">
	<link rel="stylesheet" href="css/material.min.css">
	<link rel="stylesheet" href="css/material-design-iconic-font.min.css">
	<link rel="stylesheet" href="css/jquery.mCustomScrollbar.css">
	<link rel="stylesheet" href="css/main.css">
	
    <link rel="stylesheet" href="css/bootstrap.min.css">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/jquery-1.11.2.min.js"><\/script>')</script>
	<script src="js/material.min.js" ></script>
	<script src="js/sweetalert2.min.js" ></script>
	<script src="js/jquery.mCustomScrollbar.concat.min.js" ></script>
	<script src="js/main.js" ></script>
</head>
<body>
	<!-- Notifications area -->
	
	<!-- navBar -->
	<div class="full-width navBar">
		<div class="full-width navBar-options">
			<i class="zmdi zmdi-more-vert btn-menu" id="btn-menu"></i>	
			<div class="mdl-tooltip" for="btn-menu">Menú principal</div>
			<nav class="navBar-options-list">
				<ul class="list-unstyle">
					<!-- Aquí barra de notificaciones-->
					<li class="btn-exit" id="btn-exit">
						<i class="zmdi zmdi-power"></i>
						<div class="mdl-tooltip" for="btn-exit">Salir del sistema</div>
					</li>
					<li class="text-condensedLight noLink" ><small>Usuario</small></li>
					<li class="noLink">
						<figure>
							<img src="img/avatar-male.png" alt="Avatar" class="img-responsive">
						</figure>
					</li>
				</ul>
			</nav>
		</div>
	</div>
	<!-- navLateral -->
	<section class="full-width navLateral">
		<div class="full-width navLateral-bg btn-menu"></div>
		<div class="full-width navLateral-body">
			<div class="full-width navLateral-body-logo text-center tittles">
				<i class="zmdi zmdi-close btn-menu"></i> Administración 
			</div>
			<figure class="full-width" style="height: 77px;">
				<div class="navLateral-body-cl">
					<img src="img/avatar-male.png" alt="Avatar" class="img-responsive">
				</div>
				<figcaption class="navLateral-body-cr hide-on-tablet">
					<span>
						Nombre de usuario<br>
						<small>Administrador</small>
					</span>
				</figcaption>
			</figure>
			<div class="full-width tittles navLateral-body-tittle-menu">
				<i class="zmdi zmdi-desktop-mac"></i><span class="hide-on-tablet">&nbsp; Tablero principal</span>
			</div>
			<nav class="full-width">
				<ul class="full-width list-unstyle menu-principal">
					<li class="full-width">
						<a href="inicio.html" class="full-width">
							<div class="navLateral-body-cl">
								<i class="zmdi zmdi-view-dashboard"></i>
							</div>
							<div class="navLateral-body-cr hide-on-tablet">
								INICIO
							</div>
						</a>
					</li>
					<li class="full-width divider-menu-h"></li>
					<li class="full-width">
						<a href="#!" class="full-width btn-subMenu">
							<div class="navLateral-body-cl">
								<i class="zmdi zmdi-case"></i>
							</div>
							<div class="navLateral-body-cr hide-on-tablet">
								ADMINISTRACIÓN
							</div>
							<span class="zmdi zmdi-chevron-left"></span>
						</a>
						<ul class="full-width menu-principal sub-menu-options">
						<li class="full-width">
						<a href="productos" class="full-width">
							<div class="navLateral-body-cl">
								<i class="zmdi zmdi-washing-machine"></i>
							</div>
							<div class="navLateral-body-cr hide-on-tablet">
								PRODUCTOS
							</div>
						</a>
					</li>
							<li class="full-width">
								<a href="categorias" class="full-width">
									<div class="navLateral-body-cl">
										<i class="zmdi zmdi-label"></i>
									</div>
									<div class="navLateral-body-cr hide-on-tablet">
										CATEGORIAS
									</div>
								</a>
							</li>
						</ul>
					</li>
					<li class="full-width divider-menu-h"></li>
					<li class="full-width">
						<a href="#!" class="full-width btn-subMenu">
							<div class="navLateral-body-cl">
								<i class="zmdi zmdi-face"></i>
							</div>
							<div class="navLateral-body-cr hide-on-tablet">
								USUARIOS
							</div>
							<span class="zmdi zmdi-chevron-left"></span>
						</a>
						<ul class="full-width menu-principal sub-menu-options">
							<li class="full-width">
								<a href="administradores" class="full-width">
									<div class="navLateral-body-cl">
										<i class="zmdi zmdi-account"></i>
									</div>
									<div class="navLateral-body-cr hide-on-tablet">
										ADMINISTRADORES
									</div>
								</a>
							</li>
							
						</ul>
					</li>
					<li class="full-width divider-menu-h"></li>
					<li class="full-width">
						<a href="ventas" class="full-width">
							<div class="navLateral-body-cl">
								<i class="zmdi zmdi-shopping-cart"></i>
							</div>
							<div class="navLateral-body-cr hide-on-tablet">
								VENTAS
							</div>
						</a>
					</li>
					
					<li class="full-width divider-menu-h"></li>
					<li class="full-width">
						<a href="#!" class="full-width btn-subMenu">
							<div class="navLateral-body-cl">
								<i class="zmdi zmdi-wrench"></i>
							</div>
							<div class="navLateral-body-cr hide-on-tablet">
								AJUSTES
							</div>
							<span class="zmdi zmdi-chevron-left"></span>
						</a>
						<ul class="full-width menu-principal sub-menu-options">
							<li class="full-width">
								<a href="#!" class="full-width">
									<div class="navLateral-body-cl">
										<i class="zmdi zmdi-widgets"></i>
									</div>
									<div class="navLateral-body-cr hide-on-tablet">
										OPCIÓN 1
									</div>
								</a>
							</li>
							<li class="full-width">
								<a href="#!" class="full-width">
									<div class="navLateral-body-cl">
										<i class="zmdi zmdi-widgets"></i>
									</div>
									<div class="navLateral-body-cr hide-on-tablet">
										OPCIÓN 2
									</div>
								</a>
							</li>
						</ul>
					</li>
				</ul>
			</nav>
		</div>
	</section>
	<script src="{{asset('js/jquery.js')}}"></script>
    <script src="{{asset('js/bootstrap.bundle.min.js')}}"></script>
	@yield('contenido')
	@yield('javascript')
</body>
</html>

GuantesWario/resources/views/tienda.blade.php
@extends('template1')

@section('content')
<!-- Start Content -->
<section class="container py-5">
        <div class="row">

            <div class="col-lg-3">
                <h1 class="h2 pb-4">Categorías</h1>
                <ul class="list-unstyled templatemo-accordion">
                    
                    <div class="mdl-textfield mdl-js-textfield">
                    @foreach($categorias as $categoria)
                    <div class="row">
                        <div class="col-lg-10">
                        <p><b>{{$categoria->nombre}}</b></p>
                        </div>
                        <div class="col-lg-2">
                        <form action="{{route('tienda.index',$categoria->nombre)}}">
                        <input type="hidden" name="categoria" value="{{$categoria->nombre}}">
                        <button type="submit" class="btn btn-success"><i class="fas fa-eye"></i></button>
                        </form>
                        </div>
                    </div>
                    @endforeach
                    
                </ul> 
                
            </div>

            <div class="col-lg-9">
                <div class="row">
                    <div class="col-md-6">
                        <input type="search"><i class="fas fa-search"></i>
                    </div>
                    <div class="col-md-6 pb-4">
                        
                    </div>
                </div>
                <div class="row">
                @foreach($productos as $producto)
                    <div class="col-md-4">       
                        <div class="card mb-4 product-wap rounded-0">
                            <div class="card rounded-0">
                                <img class="card-img rounded-0 img-fluid" src="img/Productos/{{$producto->imagen}}">
                                <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                    <ul class="list-unstyled">
                                        <li><a class="btn btn-success text-white mt-2" href="shop-single.html"><i class="far fa-eye"></i></a></li>
                                        <li><a class="btn btn-success text-white mt-2" href="shop-single.html"><i class="fas fa-cart-plus"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-body">
                                <a href="shop-single.html" class="h3 text-decoration-none">{{$producto->nombreP}}</a>
                                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                                    <li>Tallas: {{$producto->talla}}</li>
                                    
                                </ul>
                                
                                <p class="text-right mb-0">{{$producto->precio}}</p>
                                <div class="col-auto">
                                        <ul class="list-inline pb-3">
                                            <li class="list-inline-item text-center">
                                                Cantidad
                                                <input type="hidden" name="product-quanity" id="product-quanity" value="1">
                                            </li>
                                            <li class="list-inline-item"><span class="btn btn-success" id="btn-minus">-</span></li>
                                            <li class="list-inline-item"><span class="badge bg-secondary" id="var-value">1</span></li>
                                            <li class="list-inline-item"><span class="btn btn-success" id="btn-plus">+</span></li>
                                        </ul>
                                </div>
                            </div>
                        </div>  
                    </div>
                @endforeach
                          <div div="row">
                    <ul class="pagination pagination-lg justify-content-end">
                        <li class="page-item disabled">
                            <a class="page-link active rounded-0 mr-3 shadow-sm border-top-0 border-left-0" href="#" tabindex="-1">1</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link rounded-0 mr-3 shadow-sm border-top-0 border-left-0 text-dark" href="#">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link rounded-0 shadow-sm border-top-0 border-left-0 text-dark" href="#">3</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- End Content -->
@endsection